server:
  port: 8888
  ssl:
    enabled: false
    key-store: classpath:keystore.p12
    key-store-password: ZAQ!2wsx
    key-store-type: PKCS12
    key-alias: my-ssl

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Yuyuan1110/MoreProtein.git
          search-paths:
          - config-repo/moreprotein
          - config-repo/gateway
          default-label: process