spring:
  application:
    name: gateway
  cloud:
    config:
      uri: http://localhost:8888
    gateway:
      routes:
        - id: myService
          uri: https://localhost:8444
          predicates:
            - Path=/test/**

server:
  port: 8443
  ssl:
    enabled: false
    key-store: classpath:keystore.p12
    key-store-password: your-keystore-password
    key-store-type: PKCS12
    key-alias: my-ssl

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
