spring:
  application:
    name: moreprotein

  server:
    port: 8080

  datasource:
    url: jdbc:mysql://localhost:3306/moreprotein
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



  security:
    user:
      name: admin
      password: secret
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO
    com.moreprotein: DEBUG
