version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ZAQ!2wsx
      - MYSQL_USER=yy
      - MYSQL_PASSWORD=wang
      - MYSQL_DATABASE=moreprotein
    ports:
      - "${MYSQL_PORT:-3306:3306}"
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT:-6379:6379}"
    networks:
      - backend

  app:
    image: yuyuan1110/moreprotein:latest
    container_name: moreprotein_app
    ports:
      - "${APP_PORT:-8080:8080}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/moreprotein
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis
    networks:
      - backend

  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
      - backend

  config-server:
    image: yuyuan1110/config-server:latest
    ports:
      - "${CONFIG_SERVER_PORT:-8888:8888}"
    networks:
      - backend

  eureka-server:
    image: yuyuan1110/eureka-server:latest
    ports:
      - "${EUREKA_PORT:-8761:8761}"
    networks:
      - backend

  gateway:
    image: yuyuan1110/gateway:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "${GATEWAY_PORT:-8081:8081}"
    depends_on:
      - eureka-server
    networks:
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
